In [33]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [34]:
df = pd.read_csv('/content/drive/My Drive/Colab Notebooks/NLP/train.txt', sep = ';', header=None, names = ['text', 'emotion'])

In [35]:
df

                                                    text  emotion
0                                i didnt feel humiliated  sadness
1      i can go from feeling so hopeless to so damned...  sadness
2       im grabbing a minute to post i feel greedy wrong    anger
3      i am ever feeling nostalgic about the fireplac...     love
4                                   i am feeling grouchy    anger
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...  sadness
15996  i am now turning and i feel pathetic that i am...  sadness
15997                     i feel strong and good overall      joy
15998  i feel like this was such a rude comment and i...    anger
15999  i know a lot but i feel so stupid because i ca...  sadness

[16000 rows x 2 columns]

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16000 entries, 0 to 15999
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   text     16000 non-null  object
 1   emotion  16000 non-null  object
dtypes: object(2)
memory usage: 250.1+ KB

In [37]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [38]:
unique_emotions = df['emotion'].unique()
emotion_numbers = {}
i = 0
for emo in unique_emotions:
  emotion_numbers[emo] = i
  i+=1

df['emotion'] = df['emotion'].map(emotion_numbers)

In [39]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

In [40]:
df['text'] = df['text'].apply(lambda x: x.lower())

In [41]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

In [42]:
import string

def remove_punctuation(text):
  return text.translate(str.maketrans('', '', string.punctuation))

In [43]:
df['text'] = df['text'].apply(remove_punctuation)

In [44]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

In [45]:
def remove_numbers(text):
  new = ""
  for i in text:
    if not i.isdigit():
      new = new+i

  return new

df['text']=df['text'].apply(remove_numbers)

In [46]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

In [47]:
import re

def remove_urls(text):
  url_pattern = re.compile(r'https?://\S+|www\.\S+')
  return url_pattern.sub(r'', text)

df['text'] = df['text'].apply(remove_urls)

In [48]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

In [49]:
import re

def remove_html_tags(text):
  clean = re.compile('<.*?>')
  return re.sub(clean, '', text)

df['text'] = df['text'].apply(remove_html_tags)

In [50]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

In [51]:
def remove_emojis(text):
  new = ""
  for i in text:
    if i.isascii():
      new = new+i

  return new

df['text'] = df['text'].apply(remove_emojis)

In [52]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

In [53]:
import nltk

In [54]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [55]:
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [56]:
stop_words = set(stopwords.words('english'))

In [57]:
df.loc[1]['text']

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [58]:
word_tokenize(df.loc[1]['text'])

['i',
 'can',
 'go',
 'from',
 'feeling',
 'so',
 'hopeless',
 'to',
 'so',
 'damned',
 'hopeful',
 'just',
 'from',
 'being',
 'around',
 'someone',
 'who',
 'cares',
 'and',
 'is',
 'awake']

In [59]:
def remove(txt):
  words = word_tokenize(txt)
  cleaned = []
  for i in words:
    if not i in stop_words:
      cleaned.append(i)

  return ' '.join(cleaned)

In [60]:
df['text'] = df['text'].apply(remove)
df['text'].head()

0                                didnt feel humiliated
1    go feeling hopeless damned hopeful around some...
2            im grabbing minute post feel greedy wrong
3    ever feeling nostalgic fireplace know still pr...
4                                      feeling grouchy
Name: text, dtype: object

In [66]:
df

                                                    text  emotion
0                                  didnt feel humiliated        0
1      go feeling hopeless damned hopeful around some...        0
2              im grabbing minute post feel greedy wrong        1
3      ever feeling nostalgic fireplace know still pr...        2
4                                        feeling grouchy        1
...                                                  ...      ...
15995      brief time beanbag said anna feel like beaten        0
15996  turning feel pathetic still waiting tables sub...        0
15997                           feel strong good overall        5
15998                     feel like rude comment im glad        1
15999                       know lot feel stupid portray        0

[16000 rows x 2 columns]

In [71]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df['text'], df['emotion'], test_size=0.2, random_state=42)

In [87]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

bow_vectorizer = CountVectorizer()
tfidf_vectorizer = TfidfVectorizer()

In [90]:
X_train_bow = bow_vectorizer.fit_transform(X_train)
X_test_bow = bow_vectorizer.transform(X_test)

from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

nb_model_bow = MultinomialNB()
nb_model_bow.fit(X_train_bow, y_train)

pred_nb_bow = nb_model_bow.predict(X_test_bow)

print("Accuracy:", accuracy_score(y_test, pred_nb_bow))

Accuracy: 0.7678125

In [92]:
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

nb_model_tfidf = MultinomialNB()
nb_model_tfidf.fit(X_train_tfidf, y_train)

pred_nb_tfidf = nb_model_tfidf.predict(X_test_tfidf)

print("Accuracy:", accuracy_score(y_test, pred_nb_tfidf))

Accuracy: 0.6609375

In [93]:
from sklearn.linear_model import LogisticRegression
lr_model_bow = LogisticRegression()
lr_model_bow.fit(X_train_bow, y_train)
pred_lr_bow = lr_model_bow.predict(X_test_bow)
print("Accuracy:", accuracy_score(y_test, pred_lr_bow))

lr_model_tfidf = LogisticRegression()
lr_model_tfidf.fit(X_train_tfidf, y_train)
pred_lr_tfidf = lr_model_tfidf.predict(X_test_tfidf)
print("Accuracy:", accuracy_score(y_test, pred_lr_tfidf))

Accuracy: 0.88875
Accuracy: 0.8615625

In [94]:
from sklearn.svm import SVC
svm_model_bow = SVC()
svm_model_bow.fit(X_train_bow, y_train)
pred_svm_bow = svm_model_bow.predict(X_test_bow)
print("Accuracy:", accuracy_score(y_test, pred_svm_bow))

svm_model_tfidf = SVC()
svm_model_tfidf.fit(X_train_tfidf, y_train)
pred_svm_tfidf = svm_model_tfidf.predict(X_test_tfidf)
print("Accuracy:", accuracy_score(y_test, pred_svm_tfidf))

Accuracy: 0.8225
Accuracy: 0.8515625